package com.gastronomic.contest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllPropertiesEquals(Vote expected, Vote actual) {
        assertVoteAutoGeneratedPropertiesEquals(expected, actual);
        assertVoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllUpdatablePropertiesEquals(Vote expected, Vote actual) {
        assertVoteUpdatableFieldsEquals(expected, actual);
        assertVoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAutoGeneratedPropertiesEquals(Vote expected, Vote actual) {
        assertThat(expected)
            .as("Verify Vote auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableFieldsEquals(Vote expected, Vote actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableRelationshipsEquals(Vote expected, Vote actual) {
        assertThat(expected)
            .as("Verify Vote relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()))
            .satisfies(e -> assertThat(e.getDish()).as("check dish").isEqualTo(actual.getDish()));
    }
}
